name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v4  # Оновлено версію checkout

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4 # Оновлено версію setup-node
        with:
          node-version: '22'        # Вказана версія 22
          
      - name: Install, lint, build 🔧
        run: |
          npm install
          npm run lint:js
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
      
          
          
